local const = {
    ["prefix"] = "FV_", -- Prefix for gui element names to avoid conflicts with other mods
    ["close_button"] = "close-button", -- close button at the top right corner of each window
    ["item_selection"] = "choose-item-button", -- button in item uplink/downlink
    ["fluid_selection"] = "fluid-selection", -- button in fluid uplink/downlink
    ["udlink_checkbox"] = "uplink-downlink-checkbox", -- checkbox for udlinks used to mark them as lab surface IO
    ["entity_freq_selector_flow"] = "entity-freq-selection-flow", -- parent element of template selector for entities 
    ["entity_freq_selector"] = "entity-freq-selector", -- template selector for entities
    ["entity_freq_searchfield"] = "entity-searchfield", -- textfield element used as searchfield for template selector
    ["template_dashboard"] = "template-dashboard", -- shortcut bar element
    ["dashboard_hotkey"] = "dashboard-hotkey", -- custom input hotkey that opens dashboard
    ["dashboard_window"] = "dashboard-window",
    ["dashboard_template_selection_flow"] = "dashboard-template-selection-flow",
    ["dashboard_template_searchfield"] = "dashboard-template-searchfield",
    ["dashboard_template_selector"] = "dashboard-template-selector",
    ["dashboard_surface_selection_flow"] = "dashboard-surface-selection-flow",
    ["dashboard_surface_searchfield"] = "dashboard-surface-searchfield",
    ["dashboard_surface_selector"] = "dashboard-surface-selector",
    ["dashboard_datafield"] = "dashboard-datafield",
    ["dashboard_content_frame"] = "dashboard-content-frame",
    ["dashboard_right_content_frame"] = "dashboard-right-content-frame",
    ["surface_manager"] = "surface-manager", -- shortcut bar element 
    ["surface_manager_hotkey"] = "surface-manager-hotkey", -- custom input hotkey that opens surface manager
    ["sm_window"] = "surface-manager-window",
    ["sm_left_frame"] = "sm-left-frame",
    ["sm_selector_flow"] = "sm-selector-flow",
    ["sm_surface_selector"] = "sm-surface-selector",
    ["sm_selector_textfield"] = "sm-selector-textfield",
    ["new_surface_button"] = "new-surface-button",
    ["sm_main_flow"] = "sm-main-flow",
    ["sm_right_frame"] = "sm-right-frame",
    ["sm_new_surface_label"] = "sm-new-surface-label",
    ["sm_new_surface_textfield"] = "sm-new-surface-textfield",
    ["sm_type_dropdown"] = "sm-type-dropdown",
    ["sm_size_dropdown"] = "sm-size-dropdown",
    ["sm_energy_drain"] = "sm_energy_drain",
    ["sm_confirm_create"] = "sm-confirm-create",
    ["sm_confirmation_flow"] = "sm-confirmation-flow",
}

return const