--[[
Computation is a flow variable currently generated by template computation arrays.
It's required to sustain the existence of vsurfaces and template compilation.

Current state of computation resource is located at storage.computation.
This table is quite simple and consists only of 2 fields:
storage.computation = {
    maximum_available: number. Maximum amount of computation potentially available
    required: number. Amount of computation that is currently being used
}
--]]

local ComputationManager = {}

---Gets maximum available amount of computation
---@return number maximum_available
function ComputationManager.get_max_potential()
    return storage.computation.maximum_available
end

---Gets current computation demand
---@return number demand
function ComputationManager.get_current_demand()
    return storage.computation.required
end

---Gets the amount of currently available computation
---@return number available can not be negative
function ComputationManager.get_available_computation()
    local computation = storage.computation
    local available = math.max(
        computation.maximum_available - computation.required,
        0
    )
    return available
end

---Checks if there is a deficit in computation resource
---@return boolean status true if is a deficit (required > maximum_available)
function ComputationManager.has_computation_deficit()
    local computation = storage.computation
    return (computation.required > computation.maximum_available)
end

---Gets current computation demand ratio: fraction of computation
---currently required from providers.
---@return number fraction from the range [0, 1]
function ComputationManager.get_demand_ratio()
    local computation = storage.computation
    local maximum = computation.maximum_available
    if maximum == 0 then return 0 end
    return math.min(computation.required / maximum, 1)
end

---Adds provided amount to maximum computation potential
---@param amount number amount of computation to add (must be positive)
function ComputationManager.increase_potential(amount)
    local computation = storage.computation
    computation.maximum_available = computation.maximum_available + amount
end

---Removes provided amount from maximum computation potential
---@param amount number amount of computation to remove (must be positive)
function ComputationManager.decrease_potential(amount)
    local computation = storage.computation
    computation.maximum_available = math.max(
        computation.maximum_available - amount,
        0
    )
end

---Adds provided amount to computation demand
---@param amount number amount of computation to add (must be positive)
function ComputationManager.increase_demand(amount)
    local computation = storage.computation
    computation.required = computation.required + amount
end

---Removes provided amount from computation demand
---@param amount number amount of computation to remove (must be positive)
function ComputationManager.decrease_demand(amount)
    local computation = storage.computation
    computation.required = math.max(
        computation.required - amount,
        0
    )
end

return ComputationManager